<a href="https://colab.research.google.com/github/phucmanh1310/Helmet-Violation-Detection-Using-YOLO-and-VGG16/blob/main/3122411121_TranNguyenPhucManh_10Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BÀI TẬP LỚN**
<a id="bai-tap-lon"></a>
# **MỤC LỤC**

## [BÀI TẬP LỚN](#bai-tap-lon)
## Cấp độ 1: Nền tảng & Công cụ (Foundations)
### [BÀI 1: Thiết kế lớp OOP thể hiện tính kế thừa và đa hình](#bai-1)

### [BÀI 2: NumPy - Thư viện xử lý mảng và ma trận](#bai-2)

### [BÀI 3: PANDAS - Xử lý và phân tích dữ liệu](#bai-3)

### [BÀI 4: MatPlotLib - Trực quan hóa dữ liệu](#bai-4)

## Cấp độ 2: Machine Learning Cổ điển (Classical ML)

### [BÀI 5: K-MEANS - Thuật toán phân cụm (Clustering)](#bai-5)

### [BÀI 6: KNN - K-Nearest Neighbors (Phân loại theo láng giềng gần nhất)](#bai-6)

### [BÀI 7: Decision Tree: Mô phỏng quyết định của con người (If-else logic).](#bai-7)

## Cấp độ 3: Deep Learning & Computer Vision (Classification)

### [BÀI 8: SVM - Support Vector Machine (Máy vectơ hỗ trợ)](#bai-8)

### [BÀI 9: CNN - Convolutional Neural Network (Mạng nơ-ron tích chập)](#bai-9)

### [BÀI 10: VGG - Visual Geometry Group Network](#bai-10)



---


<a id="bai-1"></a>
# **BÀI 1: Thiết kế lớp OOP thể hiện tính kế thừa và đa hình**

## Khái niệm cơ bản:
- **Kế thừa (Inheritance):** Một lớp con có thể kế thừa các thuộc tính và phương thức từ lớp cha
- **Đa hình (Polymorphism):** Cùng một phương thức có thể có các hành vi khác nhau tùy theo đối tượng
- **Lớp cha (Base class):** Định nghĩa các phương thức trừu tượng (abstract method)
- **Lớp con (Derived class):** Cài đặt cụ thể các phương thức từ lớp cha

In [ ]:
# Lớp cơ sở (Lớp cha)
class Animal:
    """Lớp cha định nghĩa giao diện chung cho các loài động vật"""
    #Đây là phương thức khởi tạo (constructor) của lớp Animal
    def __init__(self, name):
        #self: Tham chiếu đến chính đối tượng đang được tạo (bắt buộc phải có trong phương thức của lớp).
        # Các tham số khác là giá trị truyền vào khi khởi tạo đối tượng.
        self.name = name # gán thuộc tính name của đối tượng với giá trị name truyền vào

    def speak(self): # Phương thức trừu tượng (abstract method) làm nhiệm vụ định nghĩa chung cho các lớp con
        raise NotImplementedError("Lớp con phải định nghĩa phương thức 'speak'")

    def info(self):
        """Phương thức chung cho tất cả các lớp con"""
        return f"Tên: {self.name}"

#abstract method khác với phương thức thông thường ở chỗ nó không có phần thân thực thi cụ thể trong lớp cha.
# Thay vào đó, nó yêu cầu các lớp con phải cung cấp triển khai cụ thể cho phương thức này.
# Điều này giúp đảm bảo rằng tất cả các lớp con đều tuân theo một giao diện chung,
# trong khi vẫn cho phép chúng có cách thực hiện riêng biệt.

# Lớp con kế thừa từ Animal
class Dog(Animal):
    """Lớp Dog thừa kế từ Animal và cài đặt speak() cho chó"""
    def speak(self):
        return f"{self.name} nói: Gâu Gâu!"

    def fetch(self):
        return f"{self.name} đang lấy bóng..."

# Một lớp con khác
class Cat(Animal):
    """Lớp Cat thừa kế từ Animal và cài đặt speak() cho mèo"""
    def speak(self):
        return f"{self.name} nói: Meo Meo!"

    def scratch(self):
        return f"{self.name} đang cào đồ vật..."

class Bird(Animal):
    """Thêm lớp con mới - Chim"""
    def speak(self):
        return f"{self.name} nói: Chíp Chíp!"

# Tạo các đối tượng
my_dog = Dog("Dog")
my_cat = Cat("Cat")
my_bird = Bird("Bird")

print("=" * 50)
print("THÔNG TIN CHI TIẾT:")
print("=" * 50)
print(my_dog.info())
print(my_cat.info())
print(my_bird.info())

print("\n" + "=" * 50)
print("PHƯƠNG THỨC RIÊNG CỦA TỪNG LỚP:")
print("=" * 50)
print(my_dog.fetch())
print(my_cat.scratch())

print("\n" + "=" * 50)
print("GIẢI THÍCH:")
print("=" * 50)
print("✓ **Kế thừa:** Lớp `Dog`, `Cat`, `Bird` kế thừa từ lớp `Animal`")
print("  → Chúng đều có thuộc tính `name` và phương thức `info()`")
print("  → Mỗi lớp con implement `speak()` theo cách riêng")

THÔNG TIN CHI TIẾT:
Tên: Dog
Tên: Cat
Tên: Bird

PHƯƠNG THỨC RIÊNG CỦA TỪNG LỚP:
Dog đang lấy bóng...
Cat đang cào đồ vật...

GIẢI THÍCH:
✓ **Kế thừa:** Lớp `Dog`, `Cat`, `Bird` kế thừa từ lớp `Animal`
  → Chúng đều có thuộc tính `name` và phương thức `info()`
  → Mỗi lớp con implement `speak()` theo cách riêng


In [ ]:
# Lớp cơ sở cho phương thức thanh toán
class PaymentMethod:
    """Lớp cha định nghĩa giao diện chung cho các phương thức thanh toán"""
    def __init__(self, owner_name):
        self.owner_name = owner_name

    def process_payment(self, amount):
        """Phương thức trừu tượng - lớp con phải implement"""
        raise NotImplementedError("Lớp con phải định nghĩa phương thức 'process_payment'")

# Lớp con: Thanh toán bằng thẻ tín dụng
class CreditCard(PaymentMethod):
    def __init__(self, owner_name, card_number, expiry_date): #khởi tạo thêm thuộc tính riêng của thẻ tín dụng
        super().__init__(owner_name)# Gọi constructor của lớp cha để khởi tạo thuộc tính chung
        self.card_number = card_number
        self.expiry_date = expiry_date

    def process_payment(self, amount): # Implement phương thức xử lý thanh toán thẻ tín dụng (override phương thức trừu tượng)
        # Giả lập kiểm tra thẻ và xử lý thanh toán
        print(f"✓ Xử lý thanh toán thẻ tín dụng cho {self.owner_name}")
        print(f"  → Thẻ: **** **** **** {self.card_number[-4:]} (Hết hạn: {self.expiry_date})")
        print(f"  → Số tiền: ${amount:.2f} - Thanh toán thành công qua cổng VISA/MasterCard!")
        return True  # Trả về True nếu thành công

# Lớp con: Thanh toán qua PayPal
class PayPal(PaymentMethod):
    def __init__(self, owner_name, email):
        super().__init__(owner_name)
        self.email = email

    def process_payment(self, amount): # Implement phương thức xử lý thanh toán PayPal
        # Giả lập gửi yêu cầu tới API PayPal
        print(f"✓ Xử lý thanh toán PayPal cho {self.owner_name}")
        print(f"  → Email: {self.email}")
        print(f"  → Số tiền: ${amount:.2f} - Thanh toán thành công qua PayPal API!")
        return True

# Hàm đa hình: Nhận bất kỳ PaymentMethod nào và gọi process_payment()
def checkout(payment_method, amount): # tham số payment_method có thể là CreditCard, PayPal, hoặc bất kỳ lớp con nào khác của PaymentMethod
    """
    Hàm checkout đa hình - nhận bất kỳ PaymentMethod nào và xử lý thanh toán.
    Thay vì viết riêng cho từng loại thanh toán, ta dùng đa hình để gọi chung.Giúp tái sử dụng code và mở rộng dễ dàng.
    Đây là nơi tính đa hình thể hiện rõ: Cùng một hàm hoạt động với nhiều loại thanh toán.
    """
    print(f"\n--- BẮT ĐẦU THANH TOÁN ---")
    print(f"Khách hàng: {payment_method.owner_name}")
    print(f"Số tiền: ${amount:.2f}")

    # Gọi phương thức process_payment() - đa hình ở đây!
    success = payment_method.process_payment(amount)

    if success:
        print("✅ Thanh toán hoàn tất! Đơn hàng đã được xử lý.")
    else:
        print("❌ Thanh toán thất bại. Vui lòng thử lại.")

    return success

# Ví dụ thực tế: Mô phỏng thanh toán trong cửa hàng online
def run_online_store_simulation():
    """Mô phỏng cửa hàng online với nhiều phương thức thanh toán"""
    print("=" * 70)
    print("CỬA HÀNG ONLINE: THANH TOÁN ĐA HÌNH")
    print("=" * 70)

    # Tạo các phương thức thanh toán khác nhau
    credit_card = CreditCard("Alice Johnson", "1234567890123456", "12/25")
    paypal = PayPal("Bob Smith", "bob@example.com")

    # Danh sách đơn hàng với phương thức thanh toán tương ứng
    orders = [
        (credit_card, 150.00),    # Alice mua laptop
        (paypal, 25.50),          # Bob mua sách
        (credit_card, 75.25)      # Alice mua phụ kiện
    ]

    for payment_method, amount in orders:
        checkout(payment_method, amount)
    print("-" * 70)
    print("✓ Tất cả thanh toán được xử lý thống nhất qua hàm `checkout()`")
    print("✓ Dễ dàng thêm phương thức mới (ví dụ: Crypto, Apple Pay) bằng cách thêm lớp mới mà không sửa từng hàm code!")

# Chạy ví dụ
run_online_store_simulation()

CỬA HÀNG ONLINE: THANH TOÁN ĐA HÌNH

--- BẮT ĐẦU THANH TOÁN ---
Khách hàng: Alice Johnson
Số tiền: $150.00
✓ Xử lý thanh toán thẻ tín dụng cho Alice Johnson
  → Thẻ: **** **** **** 3456 (Hết hạn: 12/25)
  → Số tiền: $150.00 - Thanh toán thành công qua cổng VISA/MasterCard!
✅ Thanh toán hoàn tất! Đơn hàng đã được xử lý.

--- BẮT ĐẦU THANH TOÁN ---
Khách hàng: Bob Smith
Số tiền: $25.50
✓ Xử lý thanh toán PayPal cho Bob Smith
  → Email: bob@example.com
  → Số tiền: $25.50 - Thanh toán thành công qua PayPal API!
✅ Thanh toán hoàn tất! Đơn hàng đã được xử lý.

--- BẮT ĐẦU THANH TOÁN ---
Khách hàng: Alice Johnson
Số tiền: $75.25
✓ Xử lý thanh toán thẻ tín dụng cho Alice Johnson
  → Thẻ: **** **** **** 3456 (Hết hạn: 12/25)
  → Số tiền: $75.25 - Thanh toán thành công qua cổng VISA/MasterCard!
✅ Thanh toán hoàn tất! Đơn hàng đã được xử lý.
----------------------------------------------------------------------
✓ Tất cả thanh toán được xử lý thống nhất qua hàm `checkout()`
✓ Dễ dàng thêm phương 

# <a id="bai-2"></a>**BÀI 2: NumPy - Thư viện xử lý mảng và ma trận**

NumPy là thư viện Python mạnh mẽ cho tính toán khoa học. Dưới đây là 10 ví dụ thực hành:

## Nội dung:
1. **Khởi tạo ma trận** - Cách tạo ma trận từ list, hằng số, số ngẫu nhiên
2. **Phép toán cơ bản** - Cộng, trừ, nhân, chia ma trận, tích vô hướng
3. **Thao tác hàng/cột** - Trích xuất, sửa đổi hàng cột
4. **Vector (mảng 1D)** - Cộng vector, tích vô hướng, nhân ma trận-vector
5. **Mảng 2D nâng cao** - Indexing, slicing, thay đổi giá trị
6. **Tách và ghép ma trận** - hstack, vstack, concatenate, split
7. **Hàm hữu ích** - sum, mean, max, min, where, filter
8. **Đại số tuyến tính** - Định thức, ma trận nghịch đảo
9. **Ma trận chuyển vị** - Transpose, kiểm tra đối xứng
10. **Hàm nâng cao** - cumsum, sort, std (độ lệch chuẩn)

In [ ]:
import numpy as np

print("=" * 60)
print("Ví dụ 1: TỔNG HỢP CÁC HÀM KHỞI TẠO MA TRẬN (NUMPY CHEATSHEET)")
print("=" * 60)

# --- PHẦN 1: KHỞI TẠO CƠ BẢN & HẰNG SỐ ---
print("\n--- 1. CƠ BẢN & HẰNG SỐ ---")

# Từ List - np.array() tạo một mảng NumPy từ một danh sách (list) Python.
mt_list = np.array([[1, 2, 3], [4, 5, 6]])
print(f"1.1 Từ List (np.array):\n{mt_list}")

# Toàn số 0 - np.zeros() tạo một mảng với kích thước đã cho và tất cả các phần tử đều bằng 0.
mt_zeros = np.zeros((2, 3), dtype=int)
print(f"\n1.2 Toàn số 0 (np.zeros):\n{mt_zeros}")

# Toàn số 1 - np.ones() tạo một mảng với kích thước đã cho và tất cả các phần tử đều bằng 1.
mt_ones = np.ones((2, 3), dtype=int)
print(f"\n1.3 Toàn số 1 (np.ones):\n{mt_ones}")

# Full giá trị tùy ý (ví dụ số 5) - np.full() tạo một mảng với kích thước đã cho và tất cả các phần tử đều có cùng một giá trị cụ thể.
mt_full = np.full((2, 3), 5)
print(f"\n1.4 Full giá trị cố định (np.full - số 5):\n{mt_full}")

# Ma trận đơn vị  (Identity matrix) - np.eye() tạo một ma trận đơn vị (ma trận vuông với đường chéo chính là 1 và các phần tử khác là 0).
mt_eye = np.eye(3, dtype=int)
print(f"\n1.5 Ma trận đơn vị (np.eye):\n{mt_eye}")


# --- PHẦN 2: KHỞI TẠO THEO DÃY SỐ (RANGE) ---
print("\n" + "-"*30)
print("--- 2. DÃY SỐ & KHOẢNG CÁCH ---")

# Arange: Giống range() của Python - np.arange() tạo một mảng với các giá trị được phân bổ đều trong một khoảng đã cho.
mt_arange = np.arange(0, 10, 2) # Từ 0 đến 10, bước nhảy 2
print(f"2.1 Dãy số (np.arange):\n{mt_arange}")

# Linspace: Chia đều khoảng cách - np.linspace() tạo một mảng với số lượng giá trị được phân bổ đều trong một khoảng đã cho.
mt_linspace = np.linspace(0, 1, 5) # 5 điểm từ 0 đến 1
print(f"\n2.2 Chia đều (np.linspace - 5 điểm từ 0->1):\n{mt_linspace}")


# --- PHẦN 3: NGẪU NHIÊN (RANDOM) ---
print("\n" + "-"*30)
print("--- 3. NGẪU NHIÊN (RANDOM) ---")

# Random Integer (Số nguyên) - np.random.randint() tạo một mảng với các số nguyên ngẫu nhiên trong một phạm vi đã cho.
mt_randint = np.random.randint(0, 10, (2, 3))
print(f"3.1 Số nguyên ngẫu nhiên (randint 0-9):\n{mt_randint}")

# Random Uniform (0 đến 1) - np.random.rand() tạo một mảng với các số thực ngẫu nhiên từ phân phối đều trong khoảng [0.0, 1.0).
mt_rand = np.random.rand(2, 2)
print(f"\n3.2 Ngẫu nhiên đều 0-1 (rand):\n{mt_rand}")

# Random Normal (Phân phối chuẩn/Gaussian) - np.random.randn() tạo một mảng với các số thực ngẫu nhiên từ phân phối chuẩn (Gaussian).
mt_randn = np.random.randn(2, 2)
print(f"\n3.3 Phân phối chuẩn (randn):\n{mt_randn}")

# Random Choice (Chọn từ danh sách có sẵn) - np.random.choice() tạo một mảng bằng cách chọn ngẫu nhiên từ một tập hợp dữ liệu đã cho.
items = [10, 20, 30, 40, 50]
mt_choice = np.random.choice(items, size=(2, 2))
print(f"\n3.4 Chọn ngẫu nhiên từ list mẫu (choice):\n{mt_choice}")

print("=" * 60)

Ví dụ 1: TỔNG HỢP CÁC HÀM KHỞI TẠO MA TRẬN (NUMPY CHEATSHEET)

--- 1. CƠ BẢN & HẰNG SỐ ---
1.1 Từ List (np.array):
[[1 2 3]
 [4 5 6]]

1.2 Toàn số 0 (np.zeros):
[[0 0 0]
 [0 0 0]]

1.3 Toàn số 1 (np.ones):
[[1 1 1]
 [1 1 1]]

1.4 Full giá trị cố định (np.full - số 5):
[[5 5 5]
 [5 5 5]]

1.5 Ma trận đơn vị (np.eye):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

------------------------------
--- 2. DÃY SỐ & KHOẢNG CÁCH ---
2.1 Dãy số (np.arange):
[0 2 4 6 8]

2.2 Chia đều (np.linspace - 5 điểm từ 0->1):
[0.   0.25 0.5  0.75 1.  ]

------------------------------
--- 3. NGẪU NHIÊN (RANDOM) ---
3.1 Số nguyên ngẫu nhiên (randint 0-9):
[[0 6 0]
 [5 4 9]]

3.2 Ngẫu nhiên đều 0-1 (rand):
[[0.43423999 0.2144591 ]
 [0.50160632 0.69420376]]

3.3 Phân phối chuẩn (randn):
[[-0.60065708  0.61062011]
 [ 0.19925758 -0.73172604]]

3.4 Chọn ngẫu nhiên từ list mẫu (choice):
[[30 30]
 [20 40]]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 2: CÁC PHÉP TOÁN CƠ BẢN TRÊN MA TRẬN")
print("=" * 60)
A= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
# Sử dụng các ma trận đã tạo ở trên
print("Ma trận A:\n", A)
print("\nMa trận B:\n", B)

# Phép cộng (Phép cộng phần tử tương ứng của hai mảng)
D = B + A
print("\nB + A =\n", D)

# Phép trừ (Phép trừ phần tử tương ứng của hai mảng)
E = B - A
print("\nB - A =\n", E)

# Phép nhân phần tử (element-wise) (Phép nhân từng phần tử tương ứng của hai mảng)
F = B * A
print("\nB * A (nhân từng phần tử):\n", F)

# Phép chia phần tử (cẩn thận với chia cho 0) (np.divide() thực hiện phép chia từng phần tử của hai mảng. 'where=A!=0' để tránh chia cho 0, 'out=np.zeros_like(A, dtype=float)' để gán 0 cho các vị trí chia cho 0)
G = np.divide(B.astype(float), A.astype(float), where=A!=0, out=np.zeros_like(A, dtype=float))
print("\nB / A (nhân từng phần tử):\n", G)

# Tích ma trận (dot product) (np.dot() thực hiện phép nhân ma trận (tích vô hướng đối với mảng 1D, tích ma trận đối với mảng 2D trở lên))
print("\nTích ma trận (A · B):")
dot_AB = np.dot(A, B)
print(dot_AB)

# Hãy kiểm tra kích thước (shape trả về một tuple chứa kích thước của mỗi chiều của mảng)
print(f"\nKích thước A: {A.shape}, Kích thước B: {B.shape}")
print(f"Kích thước A · B: {dot_AB.shape}")


VÍ DỤ 2: CÁC PHÉP TOÁN CƠ BẢN TRÊN MA TRẬN
Ma trận A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

B + A =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

B - A =
 [[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]

B * A (nhân từng phần tử):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

B / A (nhân từng phần tử):
 [[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]

Tích ma trận (A · B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Kích thước A: (3, 3), Kích thước B: (3, 3)
Kích thước A · B: (3, 3)


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 3: THAO TÁC TRÊN HÀNG VÀ CỘT")
print("=" * 60)

# Sử dụng lại ma trận A
A_copy = A.copy() # .copy() tạo một bản sao độc lập của mảng
print("Ma trận A gốc:\n", A_copy)

# Lấy hàng 0, nhân 2
row_0 = A_copy[0, :] * 2
print("\nHàng 0 nhân 2:")
print(row_0)

# Lấy cột 1, cộng 10
col_1 = A_copy[:, 1] + 10
print("\nCột 1 cộng 10:")
print(col_1)

# Thay cột 0 bằng toàn số 0
A_copy[:, 0] = 0
print("\nSau khi thay cột 0 bằng 0:")
print(A_copy)

# Lấy phần tử cụ thể
print("\nPhần tử ở hàng 1, cột 2:", A[1, 2])

# Thay đổi phần tử
A_copy[0, 0] = 99
print("\nSau khi thay A[0,0] = 99:")
print(A_copy)


VÍ DỤ 3: THAO TÁC TRÊN HÀNG VÀ CỘT
Ma trận A gốc:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Hàng 0 nhân 2:
[2 4 6]

Cột 1 cộng 10:
[12 15 18]

Sau khi thay cột 0 bằng 0:
[[0 2 3]
 [0 5 6]
 [0 8 9]]

Phần tử ở hàng 1, cột 2: 6

Sau khi thay A[0,0] = 99:
[[99  2  3]
 [ 0  5  6]
 [ 0  8  9]]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 4: VECTOR (MẢNG 1 CHIỀU)")
print("=" * 60)

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Vector v1:", v1)
print("Vector v2:", v2)

# Cộng vector (Phép cộng phần tử tương ứng của hai vector)
v_sum = v1 + v2
print("\nv1 + v2 =", v_sum)

# Tích vô hướng (dot product) (np.dot() tính tích vô hướng của hai vector)
dot_v = np.dot(v1, v2)
print("v1 · v2 =", dot_v)
print("(Tính: 1×4 + 2×5 + 3×6 = 4 + 10 + 18 =", dot_v, ")")

# Nhân ma trận với vector (np.dot() thực hiện phép nhân ma trận với vector)
print("\nNhân ma trận A với vector v1:")
result = np.dot(A, v1)
print("A · v1 =", result)

# Độ dài (norm) của vector (np.linalg.norm() tính chuẩn (norm) của vector hoặc ma trận)
norm_v1 = np.linalg.norm(v1)
print("\nĐộ dài của v1:", norm_v1)

# Tích ngoài (outer product) (np.outer() tính tích ngoài của hai vector)
outer = np.outer(v1, v2)
print("\nTích ngoài v1 ⊗ v2:\n", outer)


VÍ DỤ 4: VECTOR (MẢNG 1 CHIỀU)
Vector v1: [1 2 3]
Vector v2: [4 5 6]

v1 + v2 = [5 7 9]
v1 · v2 = 32
(Tính: 1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32 )

Nhân ma trận A với vector v1:
A · v1 = [14 32 50]

Độ dài của v1: 3.7416573867739413

Tích ngoài v1 ⊗ v2:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 5: THAO TÁC TRÊN MẢNG 2D NÂNG CAO")
print("=" * 60)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Ma trận A:\n", A)

# Lấy một phần tử (Truy cập phần tử bằng chỉ số hàng và cột)
elem = A[0, 1]
print(f"\nPhần tử A[0, 1] = {elem}")

# Lấy một hàng (Sử dụng slicing để lấy toàn bộ hàng)
row = A[1, :]
print(f"Hàng 1: {row}")

# Lấy một cột (Sử dụng slicing để lấy toàn bộ cột)
col = A[:, 2]
print(f"Cột 2: {col}")

# Cắt sub-ma trận (slicing) (Sử dụng slicing để trích xuất một phần của ma trận)
sub = A[0:2, 1:3]
print(f"\nSub-ma trận A[0:2, 1:3]:\n{sub}")

# Lấy các hàng lẻ (Sử dụng slicing với bước nhảy để chọn các hàng không liên tục)
odd_rows = A[::2, :]
print(f"\nCác hàng chỉ số chẵn (0, 2):\n{odd_rows}")

# Lấy ma trận đảo ngược (Sử dụng slicing với bước nhảy -1 để đảo ngược thứ tự các hàng và cột)
reversed_A = A[::-1, ::-1]
print(f"\nMa trận đảo ngược:\n{reversed_A}")

# Thay đổi giá trị các phần tử > 5 (Sử dụng mặt nạ boolean để chọn và thay đổi các phần tử thỏa mãn điều kiện)
A_modified = A.copy()
A_modified[A_modified > 5] = 0
print(f"\nSau khi thay các phần tử > 5 bằng 0:\n{A_modified}")


VÍ DỤ 5: THAO TÁC TRÊN MẢNG 2D NÂNG CAO
Ma trận A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Phần tử A[0, 1] = 2
Hàng 1: [4 5 6]
Cột 2: [3 6 9]

Sub-ma trận A[0:2, 1:3]:
[[2 3]
 [5 6]]

Các hàng chỉ số chẵn (0, 2):
[[1 2 3]
 [7 8 9]]

Ma trận đảo ngược:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sau khi thay các phần tử > 5 bằng 0:
[[1 2 3]
 [4 5 0]
 [0 0 0]]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 6: TÁCH VÀ GHÉP MA TRẬN")
print("=" * 60)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

print("Ma trận A:\n", A)
print("\nMa trận B:\n", B)

# Ghép dọc (vertical stack) - axis 0 (np.vstack() xếp chồng các mảng theo chiều dọc (row-wise))
print("\n--- GHÉP MA TRẬN ---")
V = np.vstack((A, B))
print("Ghép dọc (vstack):\n", V)

# Ghép ngang (horizontal stack) - axis 1 (np.hstack() xếp chồng các mảng theo chiều ngang (column-wise))
H = np.hstack((A, B))
print("\nGhép ngang (hstack):\n", H)

# Ghép tổng quát (concatenate) (np.concatenate() nối các mảng dọc theo một trục đã cho)
J = np.concatenate((A, B), axis=0)
print("\nConcatenate axis=0 (dọc):\n", J)

L = np.concatenate((A, B), axis=1)
print("\nConcatenate axis=1 (ngang):\n", L)


VÍ DỤ 6: TÁCH VÀ GHÉP MA TRẬN
Ma trận A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận B:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

--- GHÉP MA TRẬN ---
Ghép dọc (vstack):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Ghép ngang (hstack):
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]

Concatenate axis=0 (dọc):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Concatenate axis=1 (ngang):
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [ ]:
print("\n--- TÁCH MA TRẬN ---")

# Tách theo cột (horizontal split) (np.hsplit() chia một mảng thành nhiều mảng nhỏ hơn theo chiều ngang (cột))
cols = np.hsplit(B, 3)
print("Tách B thành 3 cột:")
for i, col in enumerate(cols):
    print(f"  Cột {i}:\n{col}\n")

# Tách theo hàng (vertical split) (np.vsplit() chia một mảng thành nhiều mảng nhỏ hơn theo chiều dọc (hàng))
rows = np.vsplit(B, 3)
print("Tách B thành 3 hàng:")
for i, row in enumerate(rows):
    print(f"  Hàng {i}: {row[0]}")

# Tách vector 1D (np.split() chia một mảng thành nhiều mảng con dựa trên các chỉ số đã cho)
v = np.array([10, 20, 30, 40, 50])
parts = np.split(v, [2, 4])  # tách tại vị trí index 2 và 4
print("\nVecto gốc:", v)
print("Tách vecto tại index 2 và 4:")
for i, part in enumerate(parts):
    print(f"  Phần {i}: {part}")


--- TÁCH MA TRẬN ---
Tách B thành 3 cột:
  Cột 0:
[[10]
 [13]
 [16]]

  Cột 1:
[[11]
 [14]
 [17]]

  Cột 2:
[[12]
 [15]
 [18]]

Tách B thành 3 hàng:
  Hàng 0: [10 11 12]
  Hàng 1: [13 14 15]
  Hàng 2: [16 17 18]

Vecto gốc: [10 20 30 40 50]
Tách vecto tại index 2 và 4:
  Phần 0: [10 20]
  Phần 1: [30 40]
  Phần 2: [50]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 7: CÁC HÀM NUMPY HỮU ÍCH")
print("=" * 60)

data = np.array([10, 20, 30, 40, 50])
print("Dữ liệu: ", data)

print("\n--- THỐNG KÊ CƠ BẢN ---")
print("Tổng:", np.sum(data)) # np.sum() tính tổng của tất cả các phần tử trong mảng
print("Trung bình:", np.mean(data)) # np.mean() tính giá trị trung bình của các phần tử trong mảng
print("Lớn nhất:", np.max(data)) # np.max() tìm giá trị lớn nhất trong mảng
print("Nhỏ nhất:", np.min(data)) # np.min() tìm giá trị nhỏ nhất trong mảng
print("Trung vị:", np.median(data)) # np.median() tính giá trị trung vị của các phần tử trong mảng
print("Độ lệch chuẩn:", np.std(data)) # np.std() tính độ lệch chuẩn của các phần tử trong mảng

print("\n--- LỌC VÀ TÌM KIẾM ---")
print("Vị trí của 30:", np.where(data == 30)) # np.where() trả về các chỉ số của các phần tử thỏa mãn điều kiện
print("Các số > 25:", data[data > 25]) # Lọc các phần tử bằng mặt nạ boolean
print("Các số ≤ 25:", data[data <= 25]) # Lọc các phần tử bằng mặt nạ boolean
print("Số phần tử > 25:", np.sum(data > 25)) # Đếm số phần tử thỏa mãn điều kiện bằng cách tính tổng các giá trị boolean (True=1, False=0)

print("\n--- HÀM TỔNG HỢP ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Ma trận:\n", matrix)
print("Tổng từng hàng:", np.sum(matrix, axis=1)) # np.sum(axis=1) tính tổng các phần tử theo hàng
print("Tổng từng cột:", np.sum(matrix, axis=0)) # np.sum(axis=0) tính tổng các phần tử theo cột
print("Trung bình từng hàng:", np.mean(matrix, axis=1)) # np.mean(axis=1) tính trung bình các phần tử theo hàng
print("Trung bình từng cột:", np.mean(matrix, axis=0)) # np.mean(axis=0) tính trung bình các phần tử theo cột


VÍ DỤ 7: CÁC HÀM NUMPY HỮU ÍCH
Dữ liệu:  [10 20 30 40 50]

--- THỐNG KÊ CƠ BẢN ---
Tổng: 150
Trung bình: 30.0
Lớn nhất: 50
Nhỏ nhất: 10
Trung vị: 30.0
Độ lệch chuẩn: 14.142135623730951

--- LỌC VÀ TÌM KIẾM ---
Vị trí của 30: (array([2]),)
Các số > 25: [30 40 50]
Các số ≤ 25: [10 20]
Số phần tử > 25: 3

--- HÀM TỔNG HỢP ---
Ma trận:
 [[1 2 3]
 [4 5 6]]
Tổng từng hàng: [ 6 15]
Tổng từng cột: [5 7 9]
Trung bình từng hàng: [2. 5.]
Trung bình từng cột: [2.5 3.5 4.5]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 8: ĐẠI SỐ TUYẾN TÍNH")
print("=" * 60)

M = np.array([[1, 2],
              [3, 4]], dtype=float)
print("Ma trận M:\n", M)

# Định thức (np.linalg.det() tính định thức của một ma trận vuông)
det_M = np.linalg.det(M)
print("\nĐịnh thức của M:", det_M)
print("(Tính: 1×4 - 2×3 = 4 - 6 = -2)")

# Ma trận nghịch đảo (np.linalg.inv() tính ma trận nghịch đảo của một ma trận vuông)
M_inv = np.linalg.inv(M)
print("\nMa trận nghịch đảo:\n", M_inv)

# Kiểm tra: M × M^(-1) = I (ma trận đơn vị) (np.dot() thực hiện phép nhân ma trận)
print("\nKiểm tra: M · M^(-1) =")
print(np.dot(M, M_inv))

# Rank của ma trận (np.linalg.matrix_rank() tính hạng của ma trận)
rank = np.linalg.matrix_rank(M)
print(f"\nRank của M: {rank}")

# Eigenvalue và Eigenvector (np.linalg.eig() tính các giá trị riêng và vector riêng của một ma trận vuông)
eigenvalues, eigenvectors = np.linalg.eig(M)
print("\nGiá trị riêng (eigenvalues):", eigenvalues)
print("Vectơ riêng (eigenvectors):\n", eigenvectors)


VÍ DỤ 8: ĐẠI SỐ TUYẾN TÍNH
Ma trận M:
 [[1. 2.]
 [3. 4.]]

Định thức của M: -2.0000000000000004
(Tính: 1×4 - 2×3 = 4 - 6 = -2)

Ma trận nghịch đảo:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Kiểm tra: M · M^(-1) =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Rank của M: 2

Giá trị riêng (eigenvalues): [-0.37228132  5.37228132]
Vectơ riêng (eigenvectors):
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 9: MA TRẬN CHUYỂN VỊ & KIỂM TRA ĐỐI XỨNG")
print("=" * 60)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Ma trận A:\n", A)

# Chuyển vị (transpose) (A.T hoặc np.transpose(A) trả về ma trận chuyển vị của A)
A_T = A.T
print("\nMa trận A chuyển vị (A^T):\n", A_T)

# Kiểm tra A có đối xứng không (A = A^T) (np.allclose() kiểm tra xem hai mảng có gần bằng nhau theo từng phần tử hay không)
is_symmetric = np.allclose(A, A.T)
print(f"\nA có đối xứng không? {is_symmetric}")

# Ví dụ ma trận đối xứng
S = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 9]])
print("\nMa trận đối xứng S:\n", S)
print("S chuyển vị:\n", S.T)
is_symmetric_S = np.allclose(S, S.T)
print(f"S có đối xứng không? {is_symmetric_S}")

# Ma trận chuyển vị trong tích ma trận
print("\nÁp dụng: Nếu A là m×n, thì A^T là n×m")
print(f"A có kích thước {A.shape}, A^T có kích thước {A_T.shape}")


VÍ DỤ 9: MA TRẬN CHUYỂN VỊ & KIỂM TRA ĐỐI XỨNG
Ma trận A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận A chuyển vị (A^T):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

A có đối xứng không? False

Ma trận đối xứng S:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
S chuyển vị:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
S có đối xứng không? True

Áp dụng: Nếu A là m×n, thì A^T là n×m
A có kích thước (3, 3), A^T có kích thước (3, 3)


In [ ]:
print("\n" + "=" * 60)
print("VÍ DỤ 10: CÁC HÀM NÂNG CAO (CUMSUM, SORT, STD)")
print("=" * 60)

# Dữ liệu mẫu
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
matrix_data = np.array([[3, 1, 2],
                        [9, 5, 8],
                        [4, 6, 7]])

print("Mảng 1D gốc:", arr)
print("Ma trận gốc:\n", matrix_data)

print("\n--- CUMSUM (TỔNG TÍCH LŨY) ---")
# Tổng tích lũy trên mảng 1D (np.cumsum() tính tổng tích lũy của các phần tử dọc theo một trục)
cum_sum_arr = np.cumsum(arr)
print("Tổng tích lũy (cumsum) trên mảng 1D:", cum_sum_arr)

# Tổng tích lũy trên ma trận (theo trục mặc định, tức là làm phẳng mảng) (np.cumsum() trên ma trận mặc định sẽ tính toán trên mảng đã làm phẳng)
cum_sum_matrix_flat = np.cumsum(matrix_data)
print("Tổng tích lũy (cumsum) trên ma trận (mảng phẳng):")
print(cum_sum_matrix_flat)

# Tổng tích lũy theo hàng (axis=1) (np.cumsum(axis=1) tính tổng tích lũy cho từng hàng)
cum_sum_matrix_row = np.cumsum(matrix_data, axis=1)
print("Tổng tích lũy (cumsum) theo hàng (axis=1):\n", cum_sum_matrix_row)

# Tổng tích lũy theo cột (axis=0) (np.cumsum(axis=0) tính tổng tích lũy cho từng cột)
cum_sum_matrix_col = np.cumsum(matrix_data, axis=0)
print("Tổng tích lũy (cumsum) theo cột (axis=0):\n", cum_sum_matrix_col)

print("\n--- SORT (SẮP XẾP) ---")
# Sắp xếp mảng 1D (np.sort() trả về một bản sao đã sắp xếp của mảng)
sorted_arr = np.sort(arr)
print("Mảng 1D sau khi sắp xếp (np.sort):", sorted_arr)

# Sắp xếp ma trận theo từng hàng (mặc định axis=-1 hoặc 1) (np.sort(axis=1) sắp xếp các phần tử trong mỗi hàng)
sorted_matrix_row = np.sort(matrix_data, axis=1)
print("Ma trận sau khi sắp xếp theo hàng (axis=1):\n", sorted_matrix_row)

# Sắp xếp ma trận theo từng cột (axis=0) (np.sort(axis=0) sắp xếp các phần tử trong mỗi cột)
sorted_matrix_col = np.sort(matrix_data, axis=0)
print("Ma trận sau khi sắp xếp theo cột (axis=0):\n", sorted_matrix_col)

print("\n--- STD (ĐỘ LỆCH CHUẨN) ---")
# Độ lệch chuẩn của mảng 1D (np.std() tính độ lệch chuẩn của mảng)
std_arr = np.std(arr)
print("Độ lệch chuẩn của mảng 1D (np.std):", std_arr)

# Độ lệch chuẩn của ma trận (np.std() tính độ lệch chuẩn của toàn bộ ma trận)
std_matrix = np.std(matrix_data)
print("Độ lệch chuẩn của toàn bộ ma trận:", std_matrix)

# Độ lệch chuẩn theo hàng (axis=1) (np.std(axis=1) tính độ lệch chuẩn cho từng hàng)
std_matrix_row = np.std(matrix_data, axis=1)
print("Độ lệch chuẩn theo từng hàng (axis=1):", std_matrix_row)

# Độ lệch chuẩn theo cột (axis=0) (np.std(axis=0) tính độ lệch chuẩn cho từng cột)
std_matrix_col = np.std(matrix_data, axis=0)
print("Độ lệch chuẩn theo từng cột (axis=0):", std_matrix_col)

print("=" * 60)


VÍ DỤ 10: CÁC HÀM NÂNG CAO (CUMSUM, SORT, STD)
Mảng 1D gốc: [3 1 4 1 5 9 2 6]
Ma trận gốc:
 [[3 1 2]
 [9 5 8]
 [4 6 7]]

--- CUMSUM (TỔNG TÍCH LŨY) ---
Tổng tích lũy (cumsum) trên mảng 1D: [ 3  4  8  9 14 23 25 31]
Tổng tích lũy (cumsum) trên ma trận (mảng phẳng):
[ 3  4  6 15 20 28 32 38 45]
Tổng tích lũy (cumsum) theo hàng (axis=1):
 [[ 3  4  6]
 [ 9 14 22]
 [ 4 10 17]]
Tổng tích lũy (cumsum) theo cột (axis=0):
 [[ 3  1  2]
 [12  6 10]
 [16 12 17]]

--- SORT (SẮP XẾP) ---
Mảng 1D sau khi sắp xếp (np.sort): [1 1 2 3 4 5 6 9]
Ma trận sau khi sắp xếp theo hàng (axis=1):
 [[1 2 3]
 [5 8 9]
 [4 6 7]]
Ma trận sau khi sắp xếp theo cột (axis=0):
 [[3 1 2]
 [4 5 7]
 [9 6 8]]

--- STD (ĐỘ LỆCH CHUẨN) ---
Độ lệch chuẩn của mảng 1D (np.std): 2.5708704751503917
Độ lệch chuẩn của toàn bộ ma trận: 2.581988897471611
Độ lệch chuẩn theo từng hàng (axis=1): [0.81649658 1.69967317 1.24721913]
Độ lệch chuẩn theo từng cột (axis=0): [2.62466929 2.1602469  2.62466929]


# **BÀI 3: PANDAS - Xử lý và phân tích dữ liệu**
<a id="bai-3"></a>
## Khái niệm:
- **Pandas là gì?**  Pandas là thư viện mã nguồn mở xây dựng trên nền NumPy, dùng để thao tác và phân tích dữ liệu dạng bảng (tabular data).
- Các cấu trúc dữ liệu chính:
  - **Series:** Mảng 1 chiều (như cột trong Excel)
  - **DataFrame:** Bảng 2 chiều (nhiều cột gộp lại)

## So sánh với các công cụ khác :
### Pandas vs. Excel:

+ Excel: Tốt cho nhìn trực quan, dữ liệu nhỏ (< 1 triệu dòng). Xử lý thủ công.

+ Pandas: Xử lý dữ liệu lớn (vài chục triệu dòng), tự động hóa (automation), kết hợp được với Machine Learning.

### Pandas vs. NumPy:

+ NumPy: Chỉ chứa các số (đồng nhất), truy cập qua chỉ số (index 0, 1, 2...). Tốt cho tính toán ma trận.

+ Pandas: Chứa dữ liệu hỗn hợp (số, chữ, ngày tháng...), truy cập qua nhãn (label/tên cột). Tốt cho xử lý dữ liệu thực tế.

In [7]:
#1. Khởi tạo và Cấu trúc dữ liệu
import pandas as pd
import numpy as np
# Tạo DataFrame
# df = pd.read_csv('duong_dan_file.csv') # Lệnh thực tế thường dùng
# Nhưng ta chỉ cần tạo dữ liệu giả lập để học
data = {
    'Ten': ['An', 'Binh', 'Cuong', 'Dung', 'An'],
    'Tuoi': [20, 21, 19, np.nan, 20],  # np.nan là giá trị rỗng (Not a Number)
    'Diem': [8.5, 9.0, 7.5, 8.0, 8.5],
    'Mon_Hoc': ['Toan', 'Ly', 'Hoa', 'Toan', 'Toan']
}


df = pd.DataFrame(data) # pd.DataFrame sẽ lấy dữ liệu từ data bên trên gán vào df

# --- KIẾN THỨC CỐT LÕI ---
print("Kích thước (dòng, cột):", df.shape) # Output: (5, 4)
print("Danh sách tên cột:", df.columns)
print("\nXem thông tin tổng quan (Rất quan trọng để kiểm tra dữ liệu rỗng):")
print(df.info())
# info() giúp bạn trả lời câu hỏi: "Dữ liệu có bao nhiêu dòng? Cột nào bị thiếu dữ liệu? Kiểu dữ liệu là gì?"

Kích thước (dòng, cột): (5, 4)
Danh sách tên cột: Index(['Ten', 'Tuoi', 'Diem', 'Mon_Hoc'], dtype='object')

Xem thông tin tổng quan (Rất quan trọng để kiểm tra dữ liệu rỗng):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Ten      5 non-null      object 
 1   Tuoi     4 non-null      float64
 2   Diem     5 non-null      float64
 3   Mon_Hoc  5 non-null      object 
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes
None


2. Truy xuất dữ liệu (Loc vs Iloc)
CỰC KỲ QUAN TRỌNG. Đây là câu hỏi bẫy phổ biến nhất.

.`loc[tên_dòng, tên_cột]`: Truy cập theo Nhãn (Label/Tên).

.`iloc[chỉ_số_dòng, chỉ_số_cột]`: Truy cập theo Vị trí (Index/Số thứ tự).

In [8]:
# Lấy cột 'Diem' (Trả về Series)
series_diem = df['Diem']

# Lấy dòng thứ 1 (Binh), cột thứ 2 (Diem)
# Cách 1: Dùng iloc (vị trí số)
print(df.iloc[1, 2]) # Output: 9.0 (Dòng index 1, Cột index 2)

# Cách 2: Dùng loc (tên) - Giả sử index là số, tên cột là 'Diem'
print(df.loc[1, 'Diem']) # Output: 9.0

# Lọc dữ liệu (Filtering)
# Câu hỏi: "Lấy ra danh sách sinh viên có điểm trên 8?"
hoc_sinh_gioi = df[df['Diem'] > 8]
print("\nHọc sinh giỏi:\n", hoc_sinh_gioi)

9.0
9.0

Học sinh giỏi:
     Ten  Tuoi  Diem Mon_Hoc
0    An  20.0   8.5    Toan
1  Binh  21.0   9.0      Ly
4    An  20.0   8.5    Toan
